# Generated by Django 5.1.2 on 2024-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="description",
            field=models.TextField(default="No Description"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marker",
            name="title",
            field=models.CharField(default="No Title", max_length=100),
            preserve_default=False,
        ),
    ]
