# Generated by Django 5.1.2 on 2024-11-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_marker_description_marker_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("rainfall_threshold", models.FloatField()),
                ("rainfall_level", models.FloatField(default=0.0)),
                ("road_status", models.CharField(default="Normal", max_length=10)),
            ],
        ),
    ]
