# Generated by Django 5.1.2 on 2024-11-19 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="rainfall_level",
        ),
        migrations.RemoveField(
            model_name="location",
            name="rainfall_threshold",
        ),
        migrations.RemoveField(
            model_name="location",
            name="road_status",
        ),
        migrations.AddField(
            model_name="location",
            name="city",
            field=models.CharField(default="Milan", max_length=255),
        ),
        migrations.AddField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="location",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of the location", null=True
            ),
        ),
    ]
