# Generated by Django 5.1.2 on 2024-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_remove_location_rainfall_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="description",
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.CharField(default="Milan", max_length=100),
        ),
        migrations.AlterField(
            model_name="location",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
