# Generated by Django 5.1.2 on 2024-11-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0005_remove_location_description_alter_location_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marker",
            name="disruption_type",
            field=models.CharField(default="Flood", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="marker",
            name="review",
            field=models.BooleanField(default=False),
        ),
    ]
