# Generated by Django 5.1.2 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0006_marker_disruption_type_marker_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marker",
            name="review",
        ),
        migrations.AddField(
            model_name="marker",
            name="dislike_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="marker",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
