# Generated by Django 5.1.2 on 2024-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0007_remove_marker_review_marker_dislike_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marker",
            name="disruption_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
